# Install the Logging Transfer Solution 
- name: Install the Logging Transfer Solution
  gather_facts: false
  hosts: all
  tasks:
  
    # Create registry settings
    - name: Run tasks to create registry required entries
      import_tasks: tasks/CreateRegistry.yml

    # Add scheduled tasks for uploading
    - name: Run tasks to build a schedule task on the windows server
      import_tasks: tasks/AddScheduledTask.yml
