---
# ---------------------------------------------------------------------------------------------------------#
#   Create encrypted file of password
#
# This will create encrypted password file for the event log archive upload script.
#
# IMPORTANT - VARABLE + 'storage_password' - is require for central storage
# ---------------------------------------------------------------------------------------------------------#
# Create variables to connect through jump host to target machines
- name: Role ensures that the socks tunnel is setup
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
      vars:
        acc_id: "{{ blueid_shortcode }}"
        transaction_id: "{{ tower_job_id }}"
      when: jh_ip is defined or jh1_ip is defined  # only if endpoint is behind a jumphost

- name: Create encrypted file of password
  hosts: all
  gather_facts: false
  vars:
    kyndryl_folder: 'C:\Kyndryl\'                   # Temp location to run script from
    password_file: 'Credential.enc'                 # File to store encrypted password in
    script_name: 'CreateEncryptedFile.ps1'          # Powershell script to create encrypted file
    
  tasks:
    # Check for the temp folder to store scripts into exist
    - name: Script folder check
      win_stat:
        path: "{{ kyndryl_folder }}"
      register: folder_check

    # Create temp folder if it does not exist
    - name: Create script folder if it does not exist
      win_file:
        path: "{{ kyndryl_folder }}"
        state: directory
      when: folder_check.stat.exists == false
        
    # Copy powershell script to temp folder on server
    - name: Copy Powershell file to script folder
      win_copy:
        src: "./{{ script_name }}"
        dest: "{{ kyndryl_folder }}{{ script_name }}"

    # Create a windows task schedule to create the encrypted file     
    - name: Create scheduled task to create encrypted file
      win_scheduled_task:
        name: "Create Encrypted File"
        description: "Scheduled task created by Ansible"
        actions:
        - path: powershell.exe
          arguments: >
            -File "{{ kyndryl_folder }}{{ script_name }}"
            -PassString "{{ storage_password }}"
            -SaveLocation "{{ kyndryl_folder }}{{ password_file }}" 
        state: present
        enabled: yes
        triggers:
        - type: registration
        frequency: once
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        logon_type: password
      no_log: True
 
    # Wait for the file to be create be moving on clean up 
    - name: Wait until the encrypted password file is present
      win_wait_for:
        path: "{{ kyndryl_folder }}{{ password_file }}" 
        
    # Remove Powershell file 
    - name: Remove Powershell file
      win_file:
        path: "{{ kyndryl_folder }}{{ script_name }}"
        state: absent

    # Remove the Task schedule        
    - name: Remove scheduled task
      win_scheduled_task:
        name: "Create Encrypted File"
        state: absent
